<?php
$config=[
    'addPatient'=>[
        [
            'field'=>'p_firstName',
            'label'=>'p_firstName',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'p_lastName',
            'label'=>'p_lastName',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'contact1',
            'label'=>'contact1',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'contact2',
            'label'=>'contact2',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'gender',
            'label'=>'gender',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'address',
            'label'=>'address',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'dob',
            'label'=>'dob',
            'rules'=>'required'
        ]
    ],
    'addDoctor'=>[
        [
            'field'=>'d_firstName',
            'label'=>'d_firstName',
            'rules'=>'required|alpha_numeric_spaces'
        ],[
            'field'=>'d_lastName',
            'label'=>'d_lastName',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'contact1',
            'label'=>'contact1',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'contact2',
            'label'=>'contact2',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'gender',
            'label'=>'gender',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'address',
            'label'=>'address',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'dob',
            'label'=>'dob',
            'rules'=>'required'
        ],
        [
            'field'=>'email',
            'label'=>'email',
            'rules'=>'required|valid_email'
        ]
    ],
    'addStaff'=>[
        [
            'field'=>'s_firstName',
            'label'=>'s_firstName',
            'rules'=>'required|alpha_numeric_spaces'
        ],[
            'field'=>'s_lastName',
            'label'=>'s_lastName',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'contact1',
            'label'=>'contact1',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'contact2',
            'label'=>'contact2',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'gender',
            'label'=>'gender',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'staffLevel',
            'label'=>'staffLevel',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'address',
            'label'=>'address',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'dob',
            'label'=>'dob',
            'rules'=>'required'
        ],
        [
            'field'=>'email',
            'label'=>'email',
            'rules'=>'required|valid_email'
        ]
    ],
    'addAppointment'=>[
        [
            'field'=>'appointmentDate',
            'label'=>'appointmentDate',
            'rules'=>'required|alpha_dash'
        ],
        [
            'field'=>'timeSlotId',
            'label'=>'timeSlotId',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'patientId',
            'label'=>'patientId',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'doctorId',
            'label'=>'doctorId',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'notes',
            'label'=>'notes',
            'rules'=>'alpha_dash'
        ],
    ],
    'uploadReport'=>[
        [
            'field'=>'reportTitle',
            'label'=>'reportTitle',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'patientId',
            'label'=>'patientId',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'isClear',
            'label'=>'isClear',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'reportDate',
            'label'=>'reportDate',
            'rules'=>'required|alpha_dash'
        ]
    ],
    'addVitals'=>[
        [
            'field'=>'pulse',
            'label'=>'pulse',
            'rules'=>'numeric'
        ],
        [
            'field'=>'bpUp',
            'label'=>'bpUp',
            'rules'=>'numeric'
        ],
        [
            'field'=>'bpDown',
            'label'=>'bpDown',
            'rules'=>'numeric'
        ],
        [
            'field'=>'temperature',
            'label'=>'temperature',
            'rules'=>'numeric'
        ],
        [
            'field'=>'weight',
            'label'=>'weight',
            'rules'=>'numeric'
        ],
        [
            'field'=>'height',
            'label'=>'height',
            'rules'=>'numeric'
        ],
        [
            'field'=>'appointmentIdPK',
            'label'=>'appointmentId',
            'rules'=>'required|numeric'
        ]
    ],
    'addNotes'=>[
        [
            'field'=>'appointmentStatus',
            'label'=>'Appointment Status',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'complaints',
            'label'=>'complaints',
            'rules'=>'alpha_numeric_spaces'
        ],
        [
            'field'=>'diagnosis',
            'label'=>'diagnosis',
            'rules'=>'alpha_numeric_spaces'
        ],
        [
            'field'=>'clinicalNotes',
            'label'=>'clinicalNotes',
            'rules'=>'alpha_numeric_spaces'
        ]
    ],
    /**/

    'addInvoice'=>[
        [
            'field'=>'paymentTypeId',
            'label'=>'paymentTypeId',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'amountDue',
            'label'=>'amountDue',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'discount',
            'label'=>'discount',
            'rules'=>'numeric'
        ],
        [
            'field'=>'patientId',
            'label'=>'patientId',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'paymentDate',
            'label'=>'paymentDate',
            'rules'=>'required|alpha_dash'
        ]
    ],
    'payInvoice'=>[
        [
            'field'=>'amountPaid',
            'label'=>'amountPaid',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'discount',
            'label'=>'discount',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'paymentStatus',
            'label'=>'payment Status',
            'rules'=>'required|numeric'
        ]
    ],
    /**/
    'profile_email_rule'=>[
        [
            'field'=>'userEmail',
            'label'=>'user Email',
            'rules'=>'required|valid_email|is_unique[cdb_tbl_users.userEmail]'
        ]
    ],
    'profile_userName_rule'=>[
        [
            'field'=>'userName',
            'label'=>'user Name',
            'rules'=>'required|alpha_numeric|is_unique[cdb_tbl_users.userName]'
        ]
    ],
    'profile_fields_rule'=>[
        [
            'field'=>'firstName',
            'label'=>'First Name',
            'rules'=>'required|trim|min_length[4]|alpha_numeric_spaces'
        ],
        [
            'field'=>'lastName',
            'label'=>'Last Name',
            'rules'=>'required|trim|min_length[4]|alpha_numeric_spaces'
        ],
        [
            'field'=>'secretQuestion',
            'label'=>'Secret Question',
            'rules'=>'required|min_length[3]|alpha_numeric_spaces'
        ],
        [
            'field'=>'secretAnswer',
            'label'=>'Secret Answer',
            'rules'=>'required|min_length[3]|alpha_numeric_spaces'
        ]
    ]
];
